- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/juandgaines/tasky/MainActivity.kt
- app/src/main/res/drawable/tasky_logo.xml
- app/src/main/res/values/splash.xml
- app/src/main/res/values/themes.xml
- core/presentation/designsystem/src/main/java/com/juandgaines/core/presentation/designsystem/Colors.kt
- gradle/libs.versions.toml
> feat: splash screen

- core/presentation/designsystem/src/main/java/com/juandgaines/core/presentation/designsystem/components/TaskyPasswordEditText.kt
> feat: add icon

- app/build.gradle.kts
- app/src/main/java/com/juandgaines/tasky/di/AppModule.kt
- auth/data/src/main/java/com/juandgaines/auth/data/network/AuthApi.kt
- auth/data/src/main/java/com/juandgaines/auth/data/network/RemoteAuthDataSourceImpl.kt
- auth/data/src/main/java/com/juandgaines/auth/data/network/di/AuthModule.kt
- auth/data/src/main/java/com/juandgaines/auth/data/network/refresh_token/RefreshTokenRequest.kt
- auth/data/src/main/java/com/juandgaines/auth/data/network/refresh_token/RefreshTokenResponse.kt
- auth/domain/src/main/java/com/juandgaines/auth/domain/RemoteAuthDataSource.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/AuthDataDto.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/AuthDataMapper.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/SessionManagerImpl.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/TokenApi.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/refresh_token/RefreshTokenRequest.kt
- core/data/src/main/java/com/juandgaines/core/data/auth/refresh_token/RefreshTokenResponse.kt
- core/data/src/main/java/com/juandgaines/core/data/di/RetrofitModule.kt
- core/data/src/main/java/com/juandgaines/core/data/network/NetworkExtensions.kt
- core/domain/src/main/java/com/juandgaines/core/domain/AuthData.kt
- core/domain/src/main/java/com/juandgaines/core/domain/auth/SessionManager.kt
- core/domain/src/main/java/com/juandgaines/core/domain/util/DataError.kt
- core/domain/src/main/java/com/juandgaines/core/domain/util/Error.kt
- core/domain/src/main/java/com/juandgaines/core/domain/util/Result.kt
- core/domain/src/main/java/com/juandgainescore/domain/MyClass.kt
- gradle/libs.versions.toml
- Network extensions
- RemoteAuthDataSource
- Token Api
- Session manager
> feat: netWork extensions safe call and error handling

- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/login/LoginScreen.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/login/LoginState.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/login/LoginViewModel.kt
- auth/presentation/src/main/res/values/strings.xml
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/ui/DataErrorToText.kt
- core/presentation/ui/src/main/res/values/strings.xml
- Login final details
https://github.com/user-attachments/assets/7ce377ec-6d76-42a3-ba98-054dedd8d993
> feat: nav adjustment login plus events

- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- auth/domain/src/main/java/com/juandgaines/auth/domain/PasswordValidationState.kt
- auth/domain/src/main/java/com/juandgaines/auth/domain/UserDataValidator.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/login/LoginScreen.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/login/LoginViewModel.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/register/RegisterAction.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/register/RegisterEvents.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/register/RegisterScreen.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/register/RegisterState.kt
- auth/presentation/src/main/java/com/juandgaines/auth/presentation/register/RegisterViewModel.kt
- auth/presentation/src/main/res/values/strings.xml
- Registration flow + feedback
https://github.com/user-attachments/assets/f34d9c18-2ce8-4cde-8f5e-ebd5b3961e6f
> feat: register screen

- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/DefaultReminderRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/di/ReminderModule.kt
> 1.0.1/repository reminder

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/InitialsCalculator.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/utils/DateUtils.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/componets/AgendaDatePicker.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/componets/selector_date/DateSelector.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/componets/selector_date/SelectorDayData.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/componets/selector_date/preview_providers/SelectorDayPreviewParameterProvider.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaEvents.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaViewModel.kt
- agenda/presentation/src/main/res/values/strings.xml
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- core/presentation/designsystem/src/main/java/com/juandgaines/core/presentation/designsystem/Icons.kt
- core/presentation/designsystem/src/main/java/com/juandgaines/core/presentation/designsystem/components/TaskyScaffold.kt
Date picker and initials calculator
> fix: day selector logic

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAgendaRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/DefaultReminderRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/task/DefaultTaskRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/reminder/ReminderRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/task/TaskRepository.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaEvents.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaViewModel.kt
- agenda/presentation/src/main/res/values/strings.xml
- updated task to done
- feedback messages on agenda
> feat:updated task

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/AgendaPendingSyncScheduler.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAgendaRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/workers/DeleteAgendaItemWorker.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/workers/FetchAgendaWorker.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/workers/UpdateAgendaItemWorker.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/task/DefaultTaskRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaRepository.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AgendaViewModel.kt
- core/data/schemas/com.juandgaines.core.data.database.TaskyDataBase/1.json
- core/data/src/main/java/com/juandgaines/core/data/database/AppDataBase.kt
- core/data/src/main/java/com/juandgaines/core/data/database/agenda/AgendaSyncDao.kt
- core/data/src/main/java/com/juandgaines/core/data/database/agenda/UpdateTaskSyncEntity.kt
- core/domain/src/main/java/com/juandgaines/core/domain/util/Result.kt
Agenda task update sync if fails with work manager
> 1.0.1/agenda operations list update

- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaCardMenuOperations.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaEvents.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaItemOption.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaItemUi.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/AgendaDatePicker.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/Check.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/CurrenTimeDivider.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/ProfileIcon.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/agenda_cards/AgendaCard.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/selector_date/DateSelector.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/selector_date/SelectorDayData.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/selector_date/preview_providers/SelectorDayPreviewParameterProvider.kt
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
> feat: changes on files

- agenda/data/src/main/java/com/juandgaines/agenda/data/mappers/ReminderMappers.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/mappers/TaskMappers.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/DefaultReminderRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/task/DefaultTaskRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/reminder/ReminderRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/task/TaskRepository.kt
- agenda/presentation/build.gradle.kts
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemDetails.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemEvent.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/AgendaItemTypeSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/DescriptionSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaEvents.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaItemOption.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/agenda_cards/AgendaCard.kt
- agenda/presentation/src/main/res/values/strings.xml
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- build-logic/convention/src/main/java/AndroidLibraryComposeConventionPlugin.kt
- build-logic/convention/src/main/java/com/juandgaines/convention/AndroidCompose.kt
- build-logic/convention/src/main/java/com/juandgaines/convention/ComposeDependencies.kt
- core/data/src/main/java/com/juandgaines/core/data/database/reminder/ReminderDao.kt
- core/data/src/main/java/com/juandgaines/core/data/database/task/TaskDao.kt
- core/presentation/ui/build.gradle.kts
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/navigation/ScreenNav.kt
- NAvigation from agenda to agenda item.
- First appraoch viemodel agenda item
> feat: open create item screen

- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemAction.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/DescriptionSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/edit_field/EditFieldAction.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/edit_field/EditFieldEvent.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/edit_field/EditFieldScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/edit_field/EditFieldState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/edit_field/EditFieldViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/res/values/strings.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- build-logic/convention/src/main/java/com/juandgaines/convention/ComposeDependencies.kt
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/navigation/ScreenNav.kt
> feat:edit screen field

- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/DefaultReminderRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/task/DefaultTaskRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/utils/DateUtils.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemDetails.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemEvent.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaEvents.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/res/values/strings.xml
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- auth/presentation/build.gradle.kts
- build-logic/convention/src/main/java/com/juandgaines/convention/ComposeDependencies.kt
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/agenda/AgendaItemOption.kt
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/navigation/ScreenNav.kt
- Create/ Update task and reminders
> 1.0.2/agenda item create task process

- agenda/data/src/main/AndroidManifest.xml
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/AlarmReceiver.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAlarmScheduler.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AlarmScheduler.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/AlarmReceiver.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/agenda_cards/AgendaCard.kt
- app/src/main/AndroidManifest.xml
> 1.0.3/alarm init schedule

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/receiver/AlarmAvailabilityReceiver.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AlarmProvider.kt
- agenda/presentation/src/main/AndroidManifest.xml
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaActions.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaState.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/utils/PermissionUtil.kt
- agenda/presentation/src/main/res/values/strings.xml
- core/presentation/designsystem/src/main/java/com/juandgaines/core/presentation/designsystem/components/TaskyDialog.kt
Feedback and permission handling
> 1.0.3/alarm permission handling

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/AlarmReceiver.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAlarmScheduler.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/data/src/main/res/drawable/tasky_logo.xml
- agenda/data/src/main/res/values/strings.xml
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/utils/DateUtils.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/juandgaines/tasky/MainActivity.kt
- app/src/main/java/com/juandgaines/tasky/NavigationRoot.kt
- core/presentation/ui/src/main/java/com/juandgaines/core/presentation/navigation/ScreenNav.kt
-Deeplink and notification scheduled for reminders and task
> 1.0.3/notification

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/receiver/BootReceiver.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/workers/FetchAgendaWorker.kt
> 1.0.3/sync alarm devices

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/AlarmReceiver.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAgendaRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/di/AgendaModule.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/DefaultEventRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/di/EventModule.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/remote/EventCreateResponse.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/remote/EventResponse.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/remote/UtilsEvent.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/mappers/EventMappers.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/reminder/DefaultReminderRepository.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/event/EventRepository.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemDetails.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/agenda_cards/AgendaCard.kt
- core/data/schemas/com.juandgaines.core.data.database.TaskyDataBase/1.json
- core/data/src/main/java/com/juandgaines/core/data/database/AppDataBase.kt
- core/data/src/main/java/com/juandgaines/core/data/database/event/EventDao.kt
- core/data/src/main/java/com/juandgaines/core/data/database/event/EventEntity.kt
- core/data/src/main/java/com/juandgaines/core/data/di/RetrofitModule.kt
- core/data/src/main/java/com/juandgaines/core/data/di/RoomModule.kt
- event list and event create on repository
> 1.0.4/create event repository

- agenda/data/src/main/java/com/juandgaines/agenda/data/event/di/EventModule.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/mappers/EventMappers.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemDetailsUi.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/attendee/AttendeeItem.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/attendee/AttendeeSectionFilter.kt
- core/data/src/main/AndroidManifest.xml
- core/data/src/main/java/com/juandgaines/core/data/di/ConnectivityModule.kt
- core/data/src/main/java/com/juandgaines/core/data/network/AndroidConnectivityObserver.kt
- core/domain/src/main/java/com/juandgaines/core/domain/network/ConnectivityObserver.kt
> 1.0.4/connectivity internet

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/DefaultAgendaRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/DefaultEventRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/mappers/EventMappers.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItem.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/agenda/AgendaItemDetails.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemAction.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemDetailsUi.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemEvent.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemScreen.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/DescriptionSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/StartDateSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/TitleSection.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/attendee/AttendeeItem.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/components/attendee/AttendeeSectionFilter.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/componets/agenda_cards/AgendaCard.kt
- agenda/presentation/src/main/res/values/strings.xml
- core/data/schemas/com.juandgaines.core.data.database.TaskyDataBase/1.json
- core/data/src/main/AndroidManifest.xml
- core/data/src/main/java/com/juandgaines/core/data/database/event/EventEntity.kt
- core/data/src/main/java/com/juandgaines/core/data/di/ConnectivityModule.kt
- core/data/src/main/java/com/juandgaines/core/data/network/AndroidConnectivityObserver.kt
- core/domain/src/main/java/com/juandgaines/core/domain/network/ConnectivityObserver.kt
- Join and leave as an attendee
> 1.0.5/leave event

- agenda/data/src/main/java/com/juandgaines/agenda/data/agenda/workers/DeleteAgendaItemWorker.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/DefaultAttendeeRepository.kt
- agenda/data/src/main/java/com/juandgaines/agenda/data/event/di/EventModule.kt
- agenda/domain/src/main/java/com/juandgaines/agenda/domain/event/AttendeeRepository.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/agenda_item/AgendaItemViewModel.kt
- agenda/presentation/src/main/java/com/juandgaines/agenda/presentation/home/AgendaViewModel.kt
> feat: delete agenda leave by attendee
